services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    networks:
      - tiny-click

  frontend:
    image: node:lts-alpine
    working_dir: /app
    command: npm run dev
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    networks:
      - tiny-click

  prodFrontend:
    image: httpd:2.4
    volumes:
      - ./dist:/usr/local/apache2/htdocs/
    ports:
      - "80:80"
    networks:
      - tiny-click

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: urls
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - tiny-click

networks:
  tiny-click:

volumes:
  db-data:
