services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    networks:
      - thing

  frontend:
    build:
      context: ./tiny-click
      dockerfile: Dockerfile
    volumes:
      - ./tiny-click:/app
    ports:
      - "8080:8080"
    networks:
      - thing

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: urls
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - thing

networks:
  thing:

volumes:
  db-data:
